### PR TITLE
CAS - datadir

### PR DESCRIPTION
**Pull request by pmauduit**
These modifications allows the retrieval of variables at runtime instead of at compilation time, so that the end user are able to modify the values into their properties file in the datadir instead of having to recompile the whole solution.

Note: This PR shall be addressed at the same time as the same one on CAS on the georchestra/georchestra repository. It should be merged *after* the one on CAS, or else the java import in the jsp files will fail.

TODO:
* [x] Check compilation
* [x] Check CAS server compilation

### CODE REVIEW

**Comment by pmauduit** [comment]
Compilation of the config module is OK ;
Compilation of CAS server is OK: The generated webapp contains the jsp correctly customized (via the "old" shared.maven.filter system, and includes the modifications provided by this PR).

**Comment by landryb** [comment]
Seems pretty straightforward.

**Comment by landryb** [comment]
Hm, does it also mean the properties files are read at *each* call of the cas webpage ? probably harmless on CAS since it doesnt have many many hits (and this is the behaviour we want anyway), but would be problematic on a page with gets lots of hits, no ? In the other non-CAS cases (and if i get the code right with the .init() functions) the properties files are only read once at app startup, right ?

**Comment by pmauduit** [comment]
> Hm, does it also mean the properties files are read at each call of the cas webpage ?

Since the involved files are really small (and that the kernel probably caches them when a open() syscall is made), I did not consider it as an issue, but we can maybe cache at a java level in the GeorchestraConfiguration class.

By thinking of it, we would encounter the same in mapfishapp: the newly introduced controller which produces the context configuration is scanning a directory containing the context files. When I tested it (with ~30 PIGMA contexts), the performances were still acceptable.

**Comment by pmauduit** [comment]
> Hm, does it also mean the properties files are read at each call of the cas webpage ?

In fact, it is not the case: https://github.com/georchestra/georchestra/pull/1035/files#diff-47434deef1ff3371868131c8bdd2688cR112

The properties is loaded at bean instantiation, so it is kept in memory afterwards.

**Comment by fvanderbiest** [comment]
LGTM, please merge

**Comment by pmauduit** [comment]
This should have been merged into master, not 15.06, it breaks the setup for people willing to build 15.06.

**Comment by fvanderbiest** [comment]
gosh, good thing you reverted it ... thanks Pierre.

**Pull request merged**
